### ISSUE TITLE
Changing frame limiter value changes max length of cursor tail

### ISSUE THREAD

**Issue by whizvox** [itdelatrisu/opsu#109]
If I set the frame limiter value to 240 fps, the tails for both of the cursors fade away much slower compared to when I have the value set to 60 fps, causing the tails to be very long when moving the cursor around very quickly.

Version: 0.10.0
Platform: Linux Desktop (Ubuntu 15.04)
JRE Version: 8u45 (Oracle)

**Comment by chong601** [comment]
Actually planned to report this (since it happens starting of 0.7.0). With arbitrary fps (>4000 fps), the cursortrail fades too slowly till it actually cause a Game.render() call failure.

Probably will not happen on 240 fps but if a user can move the cursor really fast, it may cause a crash because unable to render the screen)

**Comment by itdelatrisu** [comment]
Hmm, I really can't tell any difference in the cursor trail behavior between the 60 and 240 fps settings.  Is your actual framerate (if you turn on the FPS counter) 240 fps?  If it's lower than that, then that might be what's causing the issue, since the cursor trail formula currently only considers target fps (not actual fps).

**Comment by chong601** [comment]
Steps to reproduce:
Set fps to 60 (vsync)
Do circle movement on the cursor till you can see the trail
Progressively increase the fps and maintain the spin

The trail will be completely missing by 240 fps but will reappear if you spin faster

From my view, fixing this won't be easy....

**Comment by itdelatrisu** [comment]
^ It looks exactly the same at any fps setting for me.  Is there something I'm missing?

**Comment by chong601** [comment]
From what i can observe (since i managed to kind of do it but can't get recording work), if I slowly bump up the FPS while maintaining the spin speed, the cursor-trail length will get shorter on every fps increase. However, the difference is rather minor on 60-120-240 case, On 60-120-5000 (yes my custom fps setting hacked directly on the code itself), the cursortrail will never show up till i need to move the mouse so fast that the trail will suddenly show up to the level that if I keep maintaining the speed, I can cause LWJGL/Slick to crash because of failing to do Game.render() call in timely manner.

Not really a big issue but kind of inconsistent UI behavior.

Didn't try the old cursor style yet so I can't really tell...

**Comment by whizvox** [comment]
Okay, I did a little more investigation into this, and I have no clue what could be causing this. I got different results depending on the system I used.

Ubuntu 15.04: http://i.imgur.com/nPMwpTZ.png?1

Windows 7: http://i.imgur.com/ueIsvNk.png

I spun at around the same speed. As you can see, for Ubuntu, the framerate is at 61 fps, despite being locked at 240, and the cursor tail is enormous, and for Windows 7, it's working as it should. I could post specs if you want.

**Comment by itdelatrisu** [comment]
Great, thanks for the info -- that's what I guessed.  The cursor trail issue should be fixed now, but the trails are a bit off for a few seconds after changing FPS (it seems like Slick's internal framerate counter is delayed).

I have no idea why your framerate gets capped at 60 on Ubuntu, though.  I haven't received any other reports about this, so I don't know if it's an issue with Slick on the OS or just on your machine -- it's worth opening another issue if you continue to experience the problem.
