### ISSUE TITLE
Save beatmaps/config etc. XDG-conform

### ISSUE THREAD

**Issue by Lucki** [itdelatrisu/opsu#13]
Currently all is stored in the working directory.

"**$XDG_DATA_HOME** defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to **$HOME/.local/share** should be used. "

"**$XDG_CONFIG_HOME** defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to **$HOME/.config** should be used."

Pls read this carefully:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by itdelatrisu** [comment]
Is there any reason why this would be preferable?  The application is designed to be self-contained and cross-platform, and I don't see any benefits of creating files all over the place.

**Comment by NoXPhasma** [comment]
This is the Linux standard and it should be used. If there is a standard to any operating system, how to handle config/save/data files, you should use it. Especially if you design to write a program to be cross-platform, you should take notice to such standards, you don't think?

And to be more precise why this is a issue to Linux users: The home directory is **the** main folder. You don't want that to be filled with unnecessary and trivial data/folders. That's why there are those data and config folders are for. Whenever a Linux user is searching for data of a program/game or config files, he will search in those places at first.

**Comment by itdelatrisu** [comment]
That doesn't answer the question of why the application should be installed (what you're suggesting) instead of self-contained (what it is right now), since both are valid approaches.  Also, why would you be running this in ~home anyway?

**Comment by iceblade112** [comment]
opsu! runs within the directory it's in for me. Even if it's the "Linux" standard (note the quotes), that doesn't mean it's the standard for everything.

And as @itdelatrisu said, why would you put opsu! in ~home?

**Comment by NoXPhasma** [comment]
I think you both misunderstood what we are talking about. It's not about where opsu! is running or placed. It's about the path where the beatmaps and config files are placed and opsu! is searching for. This has nothing to do where the program is installed.

**Comment by itdelatrisu** [comment]
I see.  Maybe we can add a config for this, then.

**Comment by Roschan** [comment]
I am done with the directory - implementation for Linux. 
BOHverkill and I have tested the code, it is working.

Should have the Windows-User a seperate directory for configs and data too?

**Comment by itdelatrisu** [comment]
Great!  I don't think anything is needed on Windows, since the current structure mimics osu!'s directory.  Please submit a pull request when you're ready!

**Comment by itdelatrisu** [comment]
Fixed in ed2d305.

**Comment by Lucki** [comment]
Thank you. I've made a [PKGBUILD](https://aur.archlinux.org/packages/opsu-git/).
