### ISSUE TITLE
Multitouch support

### ISSUE THREAD

**Issue by LemonLake** [itdelatrisu/opsu#130]
The other day chong and I talked a little bit about adding multitouch support. We should add support for multiple cursors and whatnot so that opsu!android can work like osu!droid, i.e. one aiming finger, the others tap.

**Comment by itdelatrisu** [comment]
Is this even possible in LWJGL?

**Comment by fluddokt** [comment]
opsu!android simulates extra touches as right click at the first finger position, so I think it should be able to one aim finger and others tap.

**Comment by FenekAlfa** [comment]
Indeed, I can do streams on the android version by pressing the first note with my right index and then dragging it while alternating left index and left middle for taps.

**Comment by itdelatrisu** [comment]
@fluddokt: How did you implement that?  If it's possible without libGDX features, it'd definitely be nice to have (since I play on a touchscreen too :P).

**Comment by fluddokt** [comment]
Well libgdx api easily provides multitouch support, however it still doesn't work with the desktop version
since its backend is still LWJGL.
My implementation is here.
https://github.com/fluddokt/opsu/blob/master/src/fluddokt/opsu/fake/StateBasedGame.java#L168

Also I really can't find any easy way of getting multitouch onto desktop.

**Comment by itdelatrisu** [comment]
Yeah, that's what I thought; thanks for pointing out the code for it.  I'll close this then since it's not really feasible with the current framework.

**Comment by LemonLake** [comment]
aight neat
