### ISSUE TITLE
2B maps are unplayable

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#203]
2B maps like [Endless Tewi-ma Park](https://osu.ppy.sh/b/265177) by Lanturn ([gameplay](https://www.youtube.com/watch?v=ydw5NNrmKqY)) are meant to be difficult and unconventional, but not unplayable.

In opsu!, all clicks go to the first slider that appears until that slider finishes, so any notes that appear while the slider is still there are missed. [Auto mode](https://www.youtube.com/watch?v=kCAcdJhGTZE) shows where the click focus is at any given point (the score also stays at 100% even though it clearly missed notes, but that's another issue). Compare that with [auto mode in osu!](https://www.youtube.com/watch?v=XWqOF2sqiQU), where the focus is given to the next note. [According to Lanturn](https://www.reddit.com/r/osugame/comments/1vlw23/are_there_any_more_2b_maps/cetk488), proper 2B tracks will never have two or more notes to hit at once, but notes during sliders are okay.

The expected behaviour is to have the click focus on the next note like osu!.

System specs:
- opsu, commit 93c8ab9, built using the [AUR package](https://aur.archlinux.org/packages/opsu-git/)
- Arch Linux x64, kernel 4.1.27-ck
- OpenJDK 1.8.0_102-b14

**Comment by WolfSiZe** [comment]
same !

**Comment by itdelatrisu** [comment]
I can't think of an easy way to do this, since everything in `Game` is based off `objectIndex`.  We'd either need to:

* advance `objectIndex` early (when the next object starts, before a slider ends), and keep a list of the skipped sliders to process later.
* don't move `objectIndex`, but keep checking next objects if their start time passed, and mark them as "processed" when they are done.

Both approaches will probably be really messy.  This is pretty low-priority.

**Comment by itdelatrisu** [comment]
Fixed in 0ae010e. :)

Bad news: "Auto" mode still counts everything it misses as "perfect", but it requires way too many changes in too many places to fix this due to the current implementation.

Good news: This also fixed another old bug where combo counts were sometimes too low.  Either my slider end time calculations are wrong (long by a few milliseconds) or some normal beatmaps actually have notes barely overlapping with sliders (didn't check, but seems unlikely).

Closing since the main issue is fixed.

**Comment by tpenguinltg** [comment]
They are indeed playable now. Thanks! Your solution doesn't seem as messy as you had suggested.

I'll be sure to watch out for negative changes in regular maps.
