### ISSUE TITLE
opsu! cannot always bind to ports

### ISSUE THREAD

**Issue by GigabyteProductions** [itdelatrisu/opsu#269]
opsu! currently binds to a port as a mechanism for detecting an already running instance (because an already running instance would have already bound to the port). Not only is this problematic in multi-user environments, some environments do not allow applications to bind to ports at all. The mechanism needs to be removed or replaced to allow opsu! to run in one of those environments.

See: https://github.com/itdelatrisu/opsu/blob/e3a4d37958f3d6c8fd91a4d0f5bb3ad270fad4e7/src/itdelatrisu/opsu/Opsu.java#L122
Related to: https://github.com/itdelatrisu/opsu/issues/119

**Comment by tpenguinltg** [comment]
I agree with not binding to a port unless opsu! allows remote commands, which it doesn't as far as I know. An alternative to binding to a socket is to use a [shutdown hook and lock file](https://stackoverflow.com/a/7036134) ([code example](https://stackoverflow.com/a/24778855)).

**Comment by itdelatrisu** [comment]
Would this be solved with an "Ignore" option?  Though if an another app instance is actually open, it'll still fail to launch because the database files will be locked.

I disagree that it's a problem in a multi-user environment since you can just change the port in the config file, or if you're running from the same install directory, you can't because of the reason above (database locks).  What's an example of an environment that doesn't allow port bindings?

I didn't want to use file locks because it seems messier to handle the case where a lock file fails to get deleted.

**Comment by GigabyteProductions** [comment]
Having to change port numbers is precisely what I am referring to when I say this is a problem in multi-user environments. Unless it is a server, there's very little reason for opsu! to bind to any _static_ port. The fact that it's not even binding for communication purposes is also weird.

The problematic environment that I discovered issues with is a school-issued MacBook Air. A friend of mine wanted the game, and I discovered that Java is being disallowed bind privileges on all ports, where the same ports can be bound to by netcat. This problem can exist in any systems that use mandatory access controls. In addition to these environments, there are also such thing as _multiseat_ environments, where multiple desktop sessions can be launched and used by multiple people at the same time, on the same kernel. This is beyond hypothetical, as I have configured this before.

If lock files are too messy, could _locking files_ work? If I understand you correctly, that is already being done on the database files, so conflicting instances already cannot launch regardless of the bind, correct? If locking files is impractical in Java, lock files can be done intelligently by storing the PID of a running opsu! instance in it, and checking the validity of the lock file on startup (for example, does PID exist; is its cmdline the same that was recorded) in the event that the file was not cleaned up properly.

**Comment by Lemmmy** [comment]
why even bother rolling your own system? if the database is locked, throw an error saying the game is already running, and give the user instructions how to delete the lock file just in case its not?

**Comment by itdelatrisu** [comment]
@Lemmmy: That seems like the best solution.  I'll have to play around with it later to see how to properly check for this (right now it's just a catch-all exception).

**Comment by tpenguinltg** [comment]
@itdelatrisu: I took a quick look to see if I could solve it and I noticed that in the `init` functions for ScoreDB and BeatmapDB, when an exception occurs, the error message is printed and the exception is otherwise swallowed. Is there a reason why it isn't re-thrown?

Otherwise, the solution I found was to have a catch clause for `org.sqlite.SQLiteException` and check if `e.getResultCode() == org.sqlite.SQLiteErrorCode.SQLITE_BUSY`. If so, the database is locked and we can assume that another instance is running. I see no imports for org.sqlite packages, though, so I don't know how you'd want to handle that.

As for the case where the program crashes and leaves the DB locked, I don't think we're any worse off than before. I haven't done any intensive testing, but I think this can only happen if the JVM crashes; if the JVM is running and only the program crashes, I think the database gets unlocked. If this is true, then we have the same problem in the current version as well.

**Comment by itdelatrisu** [comment]
@tpenguinltg: Thanks for looking into it, used that solution in 9074d43.  Let me know if you run into any problems.

**Comment by GigabyteProductions** [comment]
I hadn't realized this was immediately closed, but I'd like to say that I've tested launching multiple instances. The game does not start from the same directory (as expected). Starting from another directory was still problematic, as I get lots of variations of the following, but I think the issue now is just another symptom of #226:
```
Failed to load audio file 'normal-sliderwhistle.wav'.
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
```
