### ISSUE TITLE
Bug/Suggestion regarding profiles

### ISSUE THREAD

**Issue by LatiusAuro** [itdelatrisu/opsu#280]
I just downloaded opsu! Version 0.15.0b on android as I am going to try it out on my Samsung Galaxy Tab, but there's a problem in that I can't create a new profile as the on-screen keyboard doesn't show up.

Although I would like to connect a profile to my Osu! Account if that was possible, as well.

Edit: Also, I'm unable to download files from the app at the moment.

**Comment by Lemmmy** [comment]
take this to [fluddokt/opsu](https://github.com/fluddokt/opsu/issues) - this repo does not maintain the android client

**Comment by LatiusAuro** [comment]
Ah, I see. Well, it turns out the bug was me not knowing where to tap the
screen to add my name.

**Comment by itdelatrisu** [comment]
Sorry for the late reply!
* This project is not in any way affiliated with osu!.  There's no point "connecting" an osu! account because your stats here would be meaningless (you'd just be constantly syncing).
* If you have suggestions on how to make the location to tap clearer, feel free to file another issue (though probably in the other repo, since on desktop you can just start typing without clicking anywhere).
* The download issue is because the servers are down.
