### ISSUE TITLE
Spinner is lagging on gameplay

### ISSUE THREAD

**Issue by JoltP** [itdelatrisu/opsu#387]
I don't know why everytime the spinner in opsu is lagging for my phone. When i dont move my cursor the spinner isn't lagging at all. But when i spin its starts to lag bringing me from 60-61fps to 10-ish fps. I even turned on disable spinner details in the options. Same thing happened. Can you fix this?

**Comment by Lemmmy** [comment]
This is the issue tracker for the desktop version of opsu!.
Android issues (apk download): [fluddokt/opsu](https://github.com/fluddokt/opsu/issues)
Android issues (play store): [AnirudhRahul/opsu-Android](https://github.com/AnirudhRahul/opsu-Android/issues)

**Comment by Lemmmy** [comment]
@itdelatrisu it may be worth looking into getting some contributing guidelines that redirect android users to the appropriate repos, as well as an issue template that provides helpful information (for non-crash-report issues)

**Comment by itdelatrisu** [comment]
@Lemmmy It's easy to change this in the other repos in [OpsuConstants.java](https://github.com/itdelatrisu/opsu/blob/master/src/itdelatrisu/opsu/OpsuConstants.java) (`ISSUES_URL`), but :/

**Comment by tpenguinltg** [comment]
For the record, it already _is_ changed in @fluddokt's fork ([OpsuConstants.java:45](https://github.com/fluddokt/opsu/blob/228d2132a15d9eb3413a14752a7cbbd455450b88/src/itdelatrisu/opsu/OpsuConstants.java#L45)).

I think the issue is that they're downloading it off of the same website, which has no indication that the Android version is separate and not supported by us, so they come here. The solution, then, would be to make it clear that the Android version is separate.

**Comment by Lemmmy** [comment]
The other problem is that opsu-Android sends issues to the *Play Store* instead of their GitHub issue page.
