### ISSUE TITLE
[feature] distribute as a flatpak/snap, is it possible?

### ISSUE THREAD

**Issue by user5145** [itdelatrisu/opsu#439]
flatpak and snap provide some pros and cons over java.jar

pros: 
1. desktop integration - launch from menu
2. avoid dependency issues - the newest java and controlled version of xrand and gradle/maven
3. works everywhere not only on arch
4. provide arguments and logic as a bash script for opsu :), there is a lot of it (https://docs.oracle.com/en/java/javase/11/tools/java.html), minecraft uses them too and it really makes the difference.
5. doesn't alter the source code
6. it's enough to update links to update it.
7. super easy to maintain

cons:
1. flatpak/snap has to be installed
2. without repo installation isn't user friendly
3. some people don't want to use it (like apt vs rpm, i guess)
4. snap doesn't play well without ubuntu and when flatpak is installed (i've heard so, so I'm not sure if it's true)
5. they are not mature and may disappear after a few years, may have bugs and sometimes i feel like the documentation could be better.
6. their first setup takes some time and sometimes their design is annoying (e.g. self-updating applications have to be in /var/data) 

I guess you know about it anyway, so i prepared a sample (https://github.com/user5145/io.itdelatrisu.Opsu-flatpak.git). I think that it works better, mainly because now it's possible to select java arguments.

edit:
to install 
$ flatpak-builder build-dir io.itdelatrisu.Opsu.yml --force-clean --user --install

to remove
$ flatpak remove io.itdelatrisu.Opsu
$ rm -R ~/.var/app/io.itdelatrisu.Opsu <- songs and config are there

edit2: using nvidia 410.57 and nouveau this game has a memory leak even this is enough to recreate
1. download opsu16.1
2. run /usr/lib/jvm/java-11-jdk/bin/java -Xmx1500m  -jar Downloads/opsu-0.16.1.jar
so don't be surprised if your pc dies
edit3: im not longer able to recreate...

**Comment by tpenguinltg** [comment]
Thanks for the idea!

It is my personal opinion that getting package maintainers to put it in distro repos is the best way to go, but short of that, out of the three competing formats, I think AppImage is the best (see the [comparsion table](https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison)). To get it in the menu, all you'd have to do is to put a `.desktop` file that points to it in `~/.local/share/applications`. At this point, though, apart from fixing the version of Java that this runs with, is it really worth it? We don't really need to tune the Java parameters for it to work well (not that we've tested to see if it would work better with certain flags) and the JAR really does work everywhere, not just on Arch (though the JAR in the releases isn't built with `-PXDG`).

That said, if @itdelatrisu is willing to endorse it, you're welcome to maintain it (or probably even if he doesn't, but you might have to take on support issues). As you said, it should be really easy to maintain

As for your [config](https://github.com/user5145/io.itdelatrisu.Opsu-flatpak/blob/master/io.itdelatrisu.Opsu.yml), we officially support only Java 7 and 8, so your config should specify 8, not 10.

**Comment by user5145** [comment]
if itdelatrisu is against it then i will probably still maintain that repo i created, but i'm sure i'm not able to provide professional support with my broken english... that would be a shame for the project if someone haven't understood me, though i always try to help anyway.

About flatpak and appimage. I think appimage isn't supported by gnome software and kde store, doesn't support .desktop files well enough, doesn't provide a sanbox (third party software has to be used), it isn't easy for end users to change anything in appimage where for flatpak it's enough to run it with parameters and the users never know if AppImageUpdate was implemented and i don't want to keep in my system applications that don't update. But decision is to you and im fine with appimage if appimageupdate is implemented, but something should be done with that .desktop. we know about share/applications but not everybody has to (as a junior high schooler I had problems even to start a jar file, i was searching for that -jar parameter for hours to start minecraft).

About parameters, i haven't spend too much time to tune it, average fps is probably similar about 3000 (5700fps max) on my machine but notice java has to compile the code 2 times, once to create .classs files and once to create normal native machine code as it knows on which cpu it's being run only after it was already launched so it means in production (i guess so because of this docs i linked before where they write about parameters like -Xbatch and -Xint and my understanding of c++ in which java is done and https://en.wikipedia.org/wiki/Java_virtual_machine#Bytecode_interpreter_and_just-in-time_compiler) it means that it will be slow if java doesn't compile it beforehand, what for sure can happen as java cannot predict the future it can only guess, or when pc doesn't have enough ram to keep the cache or the default values disallow to allocate more ram.

And for some reason oracle thinks that 500ms of lag is more than acceptable and call it "Lower Response Time" (https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-EE6BD9FA-EF6D-4C3E-AC5C-30B8762CDC1B). it means 2fps is acceptable for oracle but it's not acceptable for osu and opsu so at least MaxGCPauseMillis and UseG1GC should be used to improve the gameplay.

People blame java for being slow but it's not, though java doesn't know that it runs as a game so i think that some configuration should be provided especially because of the nature of the game. With java 7 and 8 where g1 is only experimental and not default someone may miss because of garbage collection, just google minecraft lag spikes and check images section. 


I want it as a flatpak/appimage because I easily forget about things in my home directory and opsu isn't avaible in opensuse's repo.
I compared lazer to opsu on java 8 and they are very similar in performance, maybe lazer has smoother mouse but im not sure. I don't know if java 10 with config is smoother than default opsu but i have feeling that animation isn't as smooth as i want it even though i have 3.5k fps. Opsu on java 8 and 10 with parameters is even more similar yesterday i thought that sliders are somehow slow and those characters coming from right and left sometimes lose frames in a comparison of java 8 to 10 but it was probably only my imagination because today i don't have that feeling but i think that when there is a lot of objects java 10 with configuration is subtly smoother but it's so short and fast that i don't really know and fps is slightly better like 3400 to 3700.


is it fine to compile opsu with source=1.8 and target=1.8 but still use java 9 or newer to run it?
and what about source=1.8 and target=1.10?

**Comment by tpenguinltg** [comment]
Actually, come to think of it, support will probably be fine here since all you're doing is packaging it, but we'll keep a close eye on it in case it's the preset environment.

You are definitely welcome to maintain a Flatpak if you're more comfortable with it and it solves your use case, just make sure you keep it up to date. I'll address some of the points you made, but please note that this isn't to tell you to use AppImage or not to use Flatpak. You'd be the one maintaining it, so you're free to do whatever you want.

On AppImage in the store, that sort of defeats the purpose. If I'm not mistaken, the store is just a front-end to the repos. But if you're looking for a listing of AppImage apps, there is a [directory](https://appimage.github.io/apps/).

On sandboxing, what you consider a downside for AppImage I actually see as a strength. It means that you can run it with whatever sandbox application you want, or none at all if you don't need sandboxing. Snap and Flatpak actually rely on the same sandboxing tools, they're just enforced and included automatically.

As for updates, the game has built-in update checks and it prompts you to download the new version if it finds one. It doesn't auto-update, though (whether that's desired functionality is another discussion).

For the `.desktop` file, even without Flatpak/Snap/AppImage, we can probably keep a `.desktop` file in the repo and tell people to edit it and put it in the right spot if they want desktop integration. For AppImage, it wouldn't be a stretch to write a wrapper script to copy a `.desktop` file into the right place (prompting the user first).

As for the Java target version, I don't have enough experience with using different versions like that. We haven't seen it surface in a while, but I think #322 is the most major issue we've come across so far. I don't know if it will be solved by using those flags, but it might be worth a shot.

As a side note, this tells me that maybe we need better installation instructions. We do have some in the [wiki](https://github.com/itdelatrisu/opsu/wiki/installation), but it's not linked to anywhere and it might be somewhat lacking.

**Comment by user5145** [comment]
Should opsu work with openjdk8u?

**Comment by tpenguinltg** [comment]
It works for me, so I'd say yes.

**Comment by user5145** [comment]
I asked because, though openjdk9+ work fine for me, openjdk8u doesn't.
"./java -jar ~/Downloads/opsu-0.16.1.jar" returns

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main" 

Opsu doesn't launch. It's the same for openjdk 192-b12 and 172-b11 which i downloaded from adoptopenjdk.net. To me it seems to be openjdk's issue. Oracle jdk8u works fine, but i cannot redistribute it.

Any idea what to do? I tried to report it to openjdk devs but i don't have an account.

**Comment by tpenguinltg** [comment]
Is there an opsu! issue already open that describes that problem? If not, then please open one and we'll try to troubleshoot. Make sure to include the stacktrace (either reproduce the error or look in the error log file) and opsu! version (if you're on the latest version, you can click the GitHub icon in the corner on the first screen and click "Copy Debug Info" to copy all of the relevant versions).

**Comment by tpenguinltg** [comment]
Linking #454

**Comment by user5145** [comment]
I don't see any need to keep this open. If someday you decide that flatpak is worth your time you know where to find a working snapshot. I wasn't really sure what i want from you so thanks for your time :) and sorry for my english.
