### ISSUE TITLE
reset account password

### ISSUE THREAD

**Issue by xctan** [itdelatrisu/opsu#467]
My id in game is `xctan`, but I cannot log in because of `Wrong Password (Username xctan already in use)`. Now I can only copy database files to login by force. Is there any possibility to reset the password?

**Comment by tpenguinltg** [comment]
There are no passwords in opsu!. Perhaps you wanted [osu!](https://osu.ppy.sh/home) proper? If so, you should probably make a post in their [forum](https://osu.ppy.sh/community/forums)

**Comment by xctan** [comment]
But there's a feature to sync across devices and a online ranking board,
which require logon.
I failed to login because of wrong password. And I have forgotten the
correct one.

**Comment by xctan** [comment]
![Screenshot_20190222-003557.png](https://i.loli.net/2019/02/22/5c6ed6153c42b.png)

![Screenshot_20190222-002530.png](https://i.loli.net/2019/02/22/5c6ed61faf1a3.png)

**Comment by UnderSampled** [comment]
I believe those features were added for by the maintainer of the Google Play version/fork, which adds a few platform specific features. You can get support for that through Google Play, or at that version's repository: https://github.com/AnirudhRahul/opsu-Android

On Feb 21, 2019 11:42 AM, xctan <notifications@github.com> wrote:
But there's a feature to sync across devices and a online ranking board,
which require logon.
I failed to login because of wrong password. And I have forgotten the
correct one.
