### ISSUE TITLE
[question] Some questions about skinning

### ISSUE THREAD

**Issue by FenekAlfa** [itdelatrisu/opsu#85]
I'm going to make a tutorial for converting skins from osu to opsu and making opsu-specific elements, and I have some questions:

1. I noticed that the logo is skinnable. Do you mind if skin makers change it?

2. Is deleting the META-INF necessary? I know it varies between applications.

3. Is there going to be a major skin breakage in the recent future? I plan to keep the tutorial updated, but there's no point in making it now if it won't be valid in a week.

4. Does opsu load SD images when it can't find an HD image and you set "Load HD images" to Yes?

5. Any requests to skinners/users using custom skins?

**Comment by itdelatrisu** [comment]
Hey, thanks for your interest!  To be honest, the skinning in opsu! is pretty awful right now, and I've been planning to actually write a skin loader when I get a chance (probably sometime over the summer, but no guarantees).  The goal is to make skinning more like osu!, where you'd be able to keep multiple skins in the `Skins/` folder and switch between them in-game, and actually read the options in `skin.ini`; there wouldn't be a need to "convert" skins from osu! once this is done, as they'd be directly compatible.

To answer your questions:
  1. One difference from osu! is that I'm not hiding any resources, which is why you can change things like the logo very easily.  This probably won't change, and I don't mind if anyone skins these images.
  2. No, don't delete anything inside the JAR.  The application won't run if you delete `META-INF`.  Just to be sure, you're putting skins in the external `Skins/` directory and not changing the JAR itself, right?
  3. See above.  File names won't change, but there will be subdirectories and a `skin.ini` in the future.
  4. Correct.  That option just searches for files suffixed with `@2x` first.
  5. opsu! doesn't have its own skin yet (just a combination of images from other skins), but if anyone is interested in creating one, shoot me a message. :P

**Comment by FenekAlfa** [comment]
> Just to be sure, you're putting skins in the external Skins/ directory and not changing the JAR itself, right?

Doesn't seem to work, unless it was added after the last release. But yeah, I was opening the JAR with an archive manager and dragging them in.

**Comment by itdelatrisu** [comment]
That was added a long time ago, and works fine for me.  Is the folder path being set correctly in the config file?

**Comment by FenekAlfa** [comment]
Where was the config file again? I'm on Linux

**Comment by itdelatrisu** [comment]
40e4495
